static_resources:

  listeners:
  - name: tcp_proxy_to_frozy
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 3031
    filter_chains:
    - filters:
        - name: envoy.tcp_proxy
          config:
            stat_prefix: ingress_tcp_proxy
            cluster: frozy_broker
            max_connect_attempts: 10

  clusters:
  # Custom Frozy broker cluster 
  - name: frozy_broker
    type: FROZY
    lb_policy: RANDOM
    connect_timeout: 1s
    hosts:
    # Listener address for accept Frozy connectors
    - socket_address:
        address: 0.0.0.0
        port_value: 7070

admin:
  access_log_path: /tmp/envoy_admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901

