FROM frolvlad/alpine-glibc

ENV loglevel=info

RUN apk upgrade --update-cache \
    && apk add dumb-init \
    && rm -rf /var/cache/apk/*

RUN mkdir -p /etc/envoy

ADD build_release_stripped/envoy /usr/local/bin/envoy
ADD configs/envoy_frozy.yaml /etc/envoy/envoy.yaml

EXPOSE 10000

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD /usr/local/bin/envoy -l $loglevel -c /etc/envoy/envoy.yaml
